### ISSUE TITLE
bestimmte Tilesets funktionieren nicht mit aktiviertem WebGL

### ISSUE THREAD

**Issue by ElianeAntonia** [DigitaleGesellschaft/workadventure-map-winterkongress#2]
Betrifft tile-set 3 und bytewerk pipoya

**Comment by znerol** [comment]
In der chromium browser console finden sich folgender Fehler:

```
WebGL: INVALID_VALUE: texImage2D: width or height out of range
createTexture2D @ phaser.js:81257
createTextureFromSource @ phaser.js:81195
init @ phaser.js:102358
initialize @ phaser.js:102319
initialize @ phaser.js:48179
create @ phaser.js:101141
addImage @ phaser.js:100624
addToCache @ phaser.js:17388
fileProcessComplete @ phaser.js:193217
onProcessComplete @ phaser.js:4792
data.onload @ phaser.js:17347
```

Offenbar gibts Probleme mit sehr grossen tilesets. Z.B.:
https://phaser.discourse.group/t/webgl-teximage2d-width-or-height-out-of-range/4037

Die maximal mögliche Grösse der tilesets ist abhängig von der Hardware. Es wäre möglich die maximale Grösse abzufragen (Stichwort `GL_MAX_TEXTURE_SIZE`). Allerdings würde das nichts bringend, weil wir die tilesets ja nicht zur Laufzeit ändern können. Auf der chromium website gibts eine Auflistung der typischen [WebGL resource limits](https://chromium.googlesource.com/angle/angle/+/HEAD/doc/ResourceLimits.md). Ich schliesse daraus, dass die tilesets nicht grösser als 2048x2048 sein sollten. Problematisch sind folgende tilesets:


```
$ find . -name '*.png' -print0 | xargs -0 ls -1S | xargs -d"\n" file | head
./tiles_png/tileset-3/d4hnezn-3844d292-7239-4608-bcc4-31254ddb37c6.png:                 PNG image data, 256 x 11000, 8-bit/color RGBA, non-interlaced
./tiles_png/community/bytewerk/cija_32x32_expansion for Pipoya_CC0.png:                 PNG image data, 480 x 4256, 8-bit/color RGBA, non-interlaced
...
```

Diese tilesets müssen in einem Grafikprogramm aufgeteilt werden.

**Comment by znerol** [comment]
Yes! Das hat funktioniert. Jetzt sehe auch ich die Infotafel und die Brüggli auf der winterlandschaft.
