### ISSUE TITLE
Animierte tiles

### ISSUE THREAD

**Issue by znerol** [DigitaleGesellschaft/workadventure-map-winterkongress#6]
Animierte tiles werden nicht angezeigt (betroffen ist die Karte `vortrag.json`).

**Comment by znerol** [comment]
Relevante issues im workadventure Projekt:

* PR: thecodingmachine/workadventure#443

Animierte tiles sind auf der CCC Instanz unterstützt, nicht aber auf derjenigen von amazee. Dort fehlt noch der PR oben.

**Comment by ElianeAntonia** [comment]
solved
